sonar.projectKey=sample-app
sonar.projectName=Sample App
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/*.spec.ts,**/node_modules/**,**/dist/**
sonar.javascript.lcov.reportPaths=coverage/sample-app/lcov.info
